### PR TITLE
Remove pmml files 

### PR DESCRIPTION
**Pull request by reikookamoto**
- Remove files in `R/` related to PMML (`pmml.R` contained main function, `nodes.R` contained helper functions specific to `recode_to_pmml()`)
- Remove mention of PMML in `README.md`
- Remove tests for `recode_to_pmml()` in `tests/testthat/`
- Remove `assets/tests/integration/expected-pmml.xml` and entire contents of `assets/tests/recode-to-pmml`
- Call `document()` from RStudio to write, edit, and remove `man/*.Rd` files & regenerate `NAMESPACE`

👀  **Removed files are now at https://github.com/Big-Life-Lab/pmml**

### CODE REVIEW

**Comment by reikookamoto** [comment]
@yulric might also be a good idea to change [this one-liner](https://github.com/Big-Life-Lab/recodeflow/blob/04bcea058c7f6e99fa6ef263b16b2b079e8be56c/DESCRIPTION#L10) that mentions PMML in the DESCRIPTION file and to state that all PMML-features have been removed in `NEWS.md` in the next release

**Review by yulric — CHANGES_REQUESTED** [review]
* Can you remove all the PMML strings from the strings.R file?
* Can you remove the following functions from utils.R? They were being used in 
PMML functions.
    * get_margins
    * get_margin_closure
    * is_left_open
    * is_right_open
    * is_numeric
    * is_rec_from_range
    * get_var_details_rows
    * get_var_details_row_indices
    * get_var_sheet_row
    * get_start_var_name
    * get_variable_type_data_type
* Remove the XML and glue package
* Remove the assets/tests/integration folder.

**Comment by yulric** [comment]
> @yulric might also be a good idea to change [this one-liner](https://github.com/Big-Life-Lab/recodeflow/blob/04bcea058c7f6e99fa6ef263b16b2b079e8be56c/DESCRIPTION#L10) that mentions PMML in the DESCRIPTION file and to state that all PMML-features have been removed in `NEWS.md` in the next release

Lets make that Description specific to recoding. Makes sense about the NEWS part.

**Comment by reikookamoto** [comment]
@yulric I agree with your suggestions with the exception of the `glue` package. I think we can keep it since I anticipate using it to write errors, warnings, and messages down the road.

**Comment by reikookamoto** [comment]
@yulric latest 4 commits respond to your earlier suggestions

**Comment by reikookamoto** [comment]
Still need to run `document()` to clean up lingering `.Rd` files

**Review by yulric — APPROVED** [review]

**Pull request merged**
